server:
  port: 9090
  servlet:
    context-path: /shiro
    jsp:
      init-parameters:
        development: true


spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com/zhangxin/mappers/*Mapper.xml
  type-aliases-package: com.zhangxin.entity
